// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod1 - Use 'RecordedMethod1Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIMotorolaMODFactoryTeWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Launch 'C:\prod\SNAP\LEFT\ModFactoryTestUI.exe'
            ApplicationUnderTest uIMotorolaMODFactoryTeWindow = ApplicationUnderTest.Launch(this.RecordedMethod1Params.UIMotorolaMODFactoryTeWindowExePath, this.RecordedMethod1Params.UIMotorolaMODFactoryTeWindowAlternateExePath);

            // Type '0000000001' in text box
            uIItemEdit.Text = this.RecordedMethod1Params.UIItemEditText;

            // Type '{Enter}' in text box
            Keyboard.SendKeys(uIItemEdit, this.RecordedMethod1Params.UIItemEditSendKeys, ModifierKeys.None);

            // Type '1111111111' in text box
            uIItemEdit.Text = this.RecordedMethod1Params.UIItemEditText1;

            // Type '' in text box
            uIItemEdit.Text = this.RecordedMethod1Params.UIItemEditText2;
        }
        
        #region Properties
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }
        
        public UIMotorolaMODFactoryTeWindow UIMotorolaMODFactoryTeWindow
        {
            get
            {
                if ((this.mUIMotorolaMODFactoryTeWindow == null))
                {
                    this.mUIMotorolaMODFactoryTeWindow = new UIMotorolaMODFactoryTeWindow();
                }
                return this.mUIMotorolaMODFactoryTeWindow;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod1Params mRecordedMethod1Params;
        
        private UIMotorolaMODFactoryTeWindow mUIMotorolaMODFactoryTeWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// Launch 'C:\prod\SNAP\LEFT\ModFactoryTestUI.exe'
        /// </summary>
        public string UIMotorolaMODFactoryTeWindowExePath = "C:\\prod\\SNAP\\LEFT\\ModFactoryTestUI.exe";
        
        /// <summary>
        /// Launch 'C:\prod\SNAP\LEFT\ModFactoryTestUI.exe'
        /// </summary>
        public string UIMotorolaMODFactoryTeWindowAlternateExePath = "C:\\prod\\SNAP\\LEFT\\ModFactoryTestUI.exe";
        
        /// <summary>
        /// Type '0000000001' in text box
        /// </summary>
        public string UIItemEditText = "0000000001";
        
        /// <summary>
        /// Type '{Enter}' in text box
        /// </summary>
        public string UIItemEditSendKeys = "{Enter}";
        
        /// <summary>
        /// Type '1111111111' in text box
        /// </summary>
        public string UIItemEditText1 = "1111111111";
        
        /// <summary>
        /// Type '' in text box
        /// </summary>
        public string UIItemEditText2 = "";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIMotorolaMODFactoryTeWindow : WinWindow
    {
        
        public UIMotorolaMODFactoryTeWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Motorola - MOD Factory Test - Version 1.0.6486.18093";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Motorola - MOD Factory Test - Version 1.0.6486.18093");
            #endregion
        }
        
        #region Properties
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow mUIItemWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Motorola - MOD Factory Test - Version 1.0.6486.18093");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("Motorola - MOD Factory Test - Version 1.0.6486.18093");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
}
