//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModFactoryTestCore {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModFactoryTestCore.en-US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing Antenna Test....
        /// </summary>
        internal static string tcAntennaTestExecuting {
            get {
                return ResourceManager.GetString("tcAntennaTestExecuting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result should be between &quot;X&quot; and &quot;Y&quot;.
        /// </summary>
        internal static string tcAntennaTestExpectedResults {
            get {
                return ResourceManager.GetString("tcAntennaTestExpectedResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antenna Test.
        /// </summary>
        internal static string tcAntennaTestName {
            get {
                return ResourceManager.GetString("tcAntennaTestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing Antenna Test....
        /// </summary>
        internal static string tcAntennaTestPreparing {
            get {
                return ResourceManager.GetString("tcAntennaTestPreparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing Battery Test....
        /// </summary>
        internal static string tcBatteryTestExecuting {
            get {
                return ResourceManager.GetString("tcBatteryTestExecuting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing Battery Test....
        /// </summary>
        internal static string tcBatteryTestPreparing {
            get {
                return ResourceManager.GetString("tcBatteryTestPreparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measures the battery voltage and check if charging..
        /// </summary>
        internal static string tcBatteryVerificationDescription {
            get {
                return ResourceManager.GetString("tcBatteryVerificationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery should be charging from MOD USB..
        /// </summary>
        internal static string tcBatteryVerificationExpectedResults {
            get {
                return ResourceManager.GetString("tcBatteryVerificationExpectedResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery Test.
        /// </summary>
        internal static string tcBatteryVerificationName {
            get {
                return ResourceManager.GetString("tcBatteryVerificationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check if battery receive charge..
        /// </summary>
        internal static string tcChargerVerificationDescription {
            get {
                return ResourceManager.GetString("tcChargerVerificationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery TP should receive charge from USB-C.
        /// </summary>
        internal static string tcChargerVerificationExpectedResults {
            get {
                return ResourceManager.GetString("tcChargerVerificationExpectedResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charger Verification..
        /// </summary>
        internal static string tcChargerVerificationName {
            get {
                return ResourceManager.GetString("tcChargerVerificationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing Charge Verification....
        /// </summary>
        internal static string tcChargeVerificationExecuting {
            get {
                return ResourceManager.GetString("tcChargeVerificationExecuting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to set all test point open..
        /// </summary>
        internal static string tcChargeVerificationFailAllTestPointOpen {
            get {
                return ResourceManager.GetString("tcChargeVerificationFailAllTestPointOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to close test point..
        /// </summary>
        internal static string tcChargeVerificationFailCloseTestPointOpen {
            get {
                return ResourceManager.GetString("tcChargeVerificationFailCloseTestPointOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to set charger 5V..
        /// </summary>
        internal static string tcChargeVerificationFailSetCharger5V {
            get {
                return ResourceManager.GetString("tcChargeVerificationFailSetCharger5V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing Charge Verification....
        /// </summary>
        internal static string tcChargeVerificationPreparing {
            get {
                return ResourceManager.GetString("tcChargeVerificationPreparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure each led voltage..
        /// </summary>
        internal static string tcLedVerificationDescription {
            get {
                return ResourceManager.GetString("tcLedVerificationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing Led Verification Test....
        /// </summary>
        internal static string tcLedVerificationExecuting {
            get {
                return ResourceManager.GetString("tcLedVerificationExecuting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All LEDS should be ON..
        /// </summary>
        internal static string tcLedVerificationExpectedResults {
            get {
                return ResourceManager.GetString("tcLedVerificationExpectedResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail on measure current leds..
        /// </summary>
        internal static string tcLedVerificationFailMeasureCurrent {
            get {
                return ResourceManager.GetString("tcLedVerificationFailMeasureCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to set charger..
        /// </summary>
        internal static string tcLedVerificationFailSetCharger {
            get {
                return ResourceManager.GetString("tcLedVerificationFailSetCharger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to turn all leds off..
        /// </summary>
        internal static string tcLedVerificationFailTurnOffAllLeds {
            get {
                return ResourceManager.GetString("tcLedVerificationFailTurnOffAllLeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to turn on all leds..
        /// </summary>
        internal static string tcLedVerificationFailTurnOnAllLeds {
            get {
                return ResourceManager.GetString("tcLedVerificationFailTurnOnAllLeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LED Verification..
        /// </summary>
        internal static string tcLedVerificationName {
            get {
                return ResourceManager.GetString("tcLedVerificationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test LED Verification PASS..
        /// </summary>
        internal static string tcLedVerificationPass {
            get {
                return ResourceManager.GetString("tcLedVerificationPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing Led Verification....
        /// </summary>
        internal static string tcLedVerificationPreparing {
            get {
                return ResourceManager.GetString("tcLedVerificationPreparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn on PSU2....
        /// </summary>
        internal static string tcLedVerificationTurnOnPSU2 {
            get {
                return ResourceManager.GetString("tcLedVerificationTurnOnPSU2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To check if LEDs are lighting.
        /// </summary>
        internal static string tcLedVerifyWithCamDescription {
            get {
                return ResourceManager.GetString("tcLedVerifyWithCamDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing LED verification with camera....
        /// </summary>
        internal static string tcLedVerifyWithCamExecuting {
            get {
                return ResourceManager.GetString("tcLedVerifyWithCamExecuting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All 4 LEDs must be recognized by the camera when they are light..
        /// </summary>
        internal static string tcLedVerifyWithCamExpectedResults {
            get {
                return ResourceManager.GetString("tcLedVerifyWithCamExpectedResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to capture frame..
        /// </summary>
        internal static string tcLedVerifyWithCamFailCaptureFrame {
            get {
                return ResourceManager.GetString("tcLedVerifyWithCamFailCaptureFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to turn all leds off..
        /// </summary>
        internal static string tcLedVerifyWithCamFailTurnOffAllLeds {
            get {
                return ResourceManager.GetString("tcLedVerifyWithCamFailTurnOffAllLeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LED Test with Camera..
        /// </summary>
        internal static string tcLedVerifyWithCamName {
            get {
                return ResourceManager.GetString("tcLedVerifyWithCamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing LED Verification with Camera....
        /// </summary>
        internal static string tcLedVerifyWithCamPreparing {
            get {
                return ResourceManager.GetString("tcLedVerifyWithCamPreparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the if the 4 magnetic points on MOD is working..
        /// </summary>
        internal static string tcMagneticDescription {
            get {
                return ResourceManager.GetString("tcMagneticDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing Magnetic Test....
        /// </summary>
        internal static string tcMagneticExecuting {
            get {
                return ResourceManager.GetString("tcMagneticExecuting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All 4 reed sensor should close when MOD is attached at fixture..
        /// </summary>
        internal static string tcMagneticExpectedResults {
            get {
                return ResourceManager.GetString("tcMagneticExpectedResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnetic Test fail to open all test pointers..
        /// </summary>
        internal static string tcMagneticFailAllTestPointOpen {
            get {
                return ResourceManager.GetString("tcMagneticFailAllTestPointOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnetic Test fail to close test point..
        /// </summary>
        internal static string tcMagneticFailCloseTestPoint {
            get {
                return ResourceManager.GetString("tcMagneticFailCloseTestPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnetic Test fail to set power on..
        /// </summary>
        internal static string tcMagneticFailSetPowerOn {
            get {
                return ResourceManager.GetString("tcMagneticFailSetPowerOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnetic Test.
        /// </summary>
        internal static string tcMagneticName {
            get {
                return ResourceManager.GetString("tcMagneticName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing Magnetic Test....
        /// </summary>
        internal static string tcMagneticPreparing {
            get {
                return ResourceManager.GetString("tcMagneticPreparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check via Mobile USB if receive the MOD communication and streaming..
        /// </summary>
        internal static string tcMobIntComDescription {
            get {
                return ResourceManager.GetString("tcMobIntComDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing Mobile Interface Communication Test....
        /// </summary>
        internal static string tcMobIntComExecuting {
            get {
                return ResourceManager.GetString("tcMobIntComExecuting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone should receive properly data information from MOD..
        /// </summary>
        internal static string tcMobIntComExpectedResults {
            get {
                return ResourceManager.GetString("tcMobIntComExpectedResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail on preparing Mobile Interface Communication..
        /// </summary>
        internal static string tcMobIntComFailPrepare {
            get {
                return ResourceManager.GetString("tcMobIntComFailPrepare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to tune frequency..
        /// </summary>
        internal static string tcMobIntComFailTuneFrequency {
            get {
                return ResourceManager.GetString("tcMobIntComFailTuneFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Interface Communication..
        /// </summary>
        internal static string tcMobIntComName {
            get {
                return ResourceManager.GetString("tcMobIntComName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing Mobile Interface Communication....
        /// </summary>
        internal static string tcMobIntComPreparing {
            get {
                return ResourceManager.GetString("tcMobIntComPreparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Interface Communication.
        /// </summary>
        internal static string tcMobIntStationCComName {
            get {
                return ResourceManager.GetString("tcMobIntStationCComName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check via Mobile USB MOD interface..
        /// </summary>
        internal static string tcMobIntStationCDescription {
            get {
                return ResourceManager.GetString("tcMobIntStationCDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing Mobile Interface Communication station C....
        /// </summary>
        internal static string tcMobIntStationCExecuting {
            get {
                return ResourceManager.GetString("tcMobIntStationCExecuting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone should receive properly data information from MOD..
        /// </summary>
        internal static string tcMobIntStationCExpectedResults {
            get {
                return ResourceManager.GetString("tcMobIntStationCExpectedResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing Mobile Interface Communication station C....
        /// </summary>
        internal static string tcMobIntStationCPreparing {
            get {
                return ResourceManager.GetString("tcMobIntStationCPreparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn the power supply ON with the current limit set to &quot;X&quot; mA.
        /// </summary>
        internal static string tcPowerOnDescription {
            get {
                return ResourceManager.GetString("tcPowerOnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing Power On Test....
        /// </summary>
        internal static string tcPowerOnExecuting {
            get {
                return ResourceManager.GetString("tcPowerOnExecuting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power supply should work below the current limit adjusted..
        /// </summary>
        internal static string tcPowerOnExpectedResults {
            get {
                return ResourceManager.GetString("tcPowerOnExpectedResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to set Power On..
        /// </summary>
        internal static string tcPowerOnFailSetPowerOn {
            get {
                return ResourceManager.GetString("tcPowerOnFailSetPowerOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power On..
        /// </summary>
        internal static string tcPowerOnName {
            get {
                return ResourceManager.GetString("tcPowerOnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing Power On....
        /// </summary>
        internal static string tcPowerOnPreparing {
            get {
                return ResourceManager.GetString("tcPowerOnPreparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measures the RSSI by phone USB..
        /// </summary>
        internal static string tctcAntennaTestDescription {
            get {
                return ResourceManager.GetString("tctcAntennaTestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measures RSSI..
        /// </summary>
        internal static string tcTunerVerificationDescription {
            get {
                return ResourceManager.GetString("tcTunerVerificationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing Tuner Verification....
        /// </summary>
        internal static string tcTunerVerificationExecuting {
            get {
                return ResourceManager.GetString("tcTunerVerificationExecuting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result should be between max value and min value..
        /// </summary>
        internal static string tcTunerVerificationExpectedResults {
            get {
                return ResourceManager.GetString("tcTunerVerificationExpectedResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail on executingTuner Verification..
        /// </summary>
        internal static string tcTunerVerificationFailExecuting {
            get {
                return ResourceManager.GetString("tcTunerVerificationFailExecuting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to get RSSI measure..
        /// </summary>
        internal static string tcTunerVerificationFailGetRssi {
            get {
                return ResourceManager.GetString("tcTunerVerificationFailGetRssi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail on preparing Tuner Verification..
        /// </summary>
        internal static string tcTunerVerificationFailPreparing {
            get {
                return ResourceManager.GetString("tcTunerVerificationFailPreparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to tune frequency..
        /// </summary>
        internal static string tcTunerVerificationFailTuneFrequency {
            get {
                return ResourceManager.GetString("tcTunerVerificationFailTuneFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency has no signal..
        /// </summary>
        internal static string tcTunerVerificationFrequencyHasNoSignal {
            get {
                return ResourceManager.GetString("tcTunerVerificationFrequencyHasNoSignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuner Verification..
        /// </summary>
        internal static string tcTunerVerificationName {
            get {
                return ResourceManager.GetString("tcTunerVerificationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing Tune Verification Test....
        /// </summary>
        internal static string tcTunerVerificationPreparing {
            get {
                return ResourceManager.GetString("tcTunerVerificationPreparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose what station test is this image. (Left or Right station test).
        /// </summary>
        internal static string uiCameraCalibrationDetails {
            get {
                return ResourceManager.GetString("uiCameraCalibrationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm if this image is from .
        /// </summary>
        internal static string uiCameraCalibrationDetailsConfirm {
            get {
                return ResourceManager.GetString("uiCameraCalibrationDetailsConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera setup calibration.
        /// </summary>
        internal static string uiCameraCalibrationTitle {
            get {
                return ResourceManager.GetString("uiCameraCalibrationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not open or read trackid file..
        /// </summary>
        internal static string uiCantReadTrackidFile {
            get {
                return ResourceManager.GetString("uiCantReadTrackidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plug both phones to run a test..
        /// </summary>
        internal static string uiCellCalibrationInsertBothCell {
            get {
                return ResourceManager.GetString("uiCellCalibrationInsertBothCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plug the left JIG cell phone..
        /// </summary>
        internal static string uiCellCalibrationInsertLeftCell {
            get {
                return ResourceManager.GetString("uiCellCalibrationInsertLeftCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plug the right JIG cell phone..
        /// </summary>
        internal static string uiCellCalibrationInsertRightCell {
            get {
                return ResourceManager.GetString("uiCellCalibrationInsertRightCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The left cell number is: .
        /// </summary>
        internal static string uiCellCalibrationLeftCellNumber {
            get {
                return ResourceManager.GetString("uiCellCalibrationLeftCellNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unplug the two cellphones from the computer..
        /// </summary>
        internal static string uiCellCalibrationRemoveCell {
            get {
                return ResourceManager.GetString("uiCellCalibrationRemoveCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unplug the left JIG cell phone..
        /// </summary>
        internal static string uiCellCalibrationRemoveLeftCell {
            get {
                return ResourceManager.GetString("uiCellCalibrationRemoveLeftCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unplug the right JIG cell phone..
        /// </summary>
        internal static string uiCellCalibrationRemoveRightCell {
            get {
                return ResourceManager.GetString("uiCellCalibrationRemoveRightCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error to configure cell phones..
        /// </summary>
        internal static string uiCellCalibrationResultError {
            get {
                return ResourceManager.GetString("uiCellCalibrationResultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell phones configured successfully !.
        /// </summary>
        internal static string uiCellCalibrationResultSuccess {
            get {
                return ResourceManager.GetString("uiCellCalibrationResultSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The right cell number is: .
        /// </summary>
        internal static string uiCellCalibrationRightCellNumber {
            get {
                return ResourceManager.GetString("uiCellCalibrationRightCellNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please follow the steps below for the correct configuration of the cell phones in their respective test station.
        /// </summary>
        internal static string uiCellCalibrationTitle {
            get {
                return ResourceManager.GetString("uiCellCalibrationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking if cover&apos;s jig is closed....
        /// </summary>
        internal static string uiCheckIfJigIsClosed {
            get {
                return ResourceManager.GetString("uiCheckIfJigIsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jig not open. Please open jig..
        /// </summary>
        internal static string uiCheckIfJigIsOpen {
            get {
                return ResourceManager.GetString("uiCheckIfJigIsOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File TestConfig.ini not found..
        /// </summary>
        internal static string uiConfigTestFileNotFound {
            get {
                return ResourceManager.GetString("uiConfigTestFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail pre conditions to start tests..
        /// </summary>
        internal static string uiFailToStartTests {
            get {
                return ResourceManager.GetString("uiFailToStartTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing Tests....
        /// </summary>
        internal static string uiInitializingTests {
            get {
                return ResourceManager.GetString("uiInitializingTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date range..
        /// </summary>
        internal static string uiInvalidDateInterval {
            get {
                return ResourceManager.GetString("uiInvalidDateInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid TrackId number..
        /// </summary>
        internal static string uiInvalidTrackId {
            get {
                return ResourceManager.GetString("uiInvalidTrackId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jig not closed. Please close Jig..
        /// </summary>
        internal static string uiJigNotClosed {
            get {
                return ResourceManager.GetString("uiJigNotClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Files not found..
        /// </summary>
        internal static string uiLogFilesNotFound {
            get {
                return ResourceManager.GetString("uiLogFilesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running recycle test =&gt; .
        /// </summary>
        internal static string uiRunningRecycle {
            get {
                return ResourceManager.GetString("uiRunningRecycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting test of TrackId = .
        /// </summary>
        internal static string uiStartTest {
            get {
                return ResourceManager.GetString("uiStartTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Action Required !.
        /// </summary>
        internal static string uiUserActionRequired {
            get {
                return ResourceManager.GetString("uiUserActionRequired", resourceCulture);
            }
        }
    }
}
